services:
  postgres:
    image: 'postgres:16.1-alpine'
    environment:
      - 'POSTGRES_DB=banques'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
  pgadmin:
    image: 'dpage/pgadmin4:7.8'
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=admin@admin.com'
      - 'PGADMIN_DEFAULT_PASSWORD=admin'
    ports:
        - '81:80'