api:
  version: '1.0'
  name: 'Banque API'
  description: 'API pour la gestion des établissements bancaires'

spring:
  datasource:
    url: jdbc:postgresql:banques
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer



kafka:
  domain-topic: banque-domain

workflow-service:
  url: http://localhost:8081
  workflow-id: 'BANQUES'



