server:
  port: 8081

---
spring:
  config:
    activate:
      on-profile:
        - prod
  data:
    mongodb:
      uri: mongodb://localhost:27017/workflow

springdoc:
  api-docs:
    enabled: false


