version: '3.3'

services:
  postgres:
    image: 'postgres:16.1-alpine'
    environment:
      - 'POSTGRES_DB=banques'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'

