version: '3.3'

services:
  workflow-service:
    image: dthibau/bceao-worflow-service:1.0
    container_name: workflow-service
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://workflow-mongodb:27017/workflow
    depends_on:
      - workflow-mongodb
    networks:
      - mongo-cluster
  workflow-mongodb:
    image: mongo:latest
    container_name: workflow-mongodb
    ports:
      - "27017:27017"
    volumes:
      - bceao-mongo:/data/db
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - mongo-cluster


  kafka:
    image: docker.io/bitnami/kafka:3.4
    container_name: kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092,EXTERNAL://kafka:9094
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - BITNAMI_DEBUG=yes
      - KAFKA_CFG_NUM_PARTITIONS=2
    networks:
      - kafka-cluster

  redpanda:
    image : docker.redpanda.com/redpandadata/console:latest
    container_name: redpanda
    ports:
      - 9090:8080
    restart: unless-stopped
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKERS=kafka:9094
    networks:
      - kafka-cluster


networks:
  kafka-cluster:
  mongo-cluster:

volumes:
  bceao-mongo:
  kafka_data:
    driver: local